/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RecantoRouteImport } from './routes/recanto'
import { Route as IndexRouteImport } from './routes/index'

const RecantoRoute = RecantoRouteImport.update({
  id: '/recanto',
  path: '/recanto',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/recanto': typeof RecantoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/recanto': typeof RecantoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/recanto': typeof RecantoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/recanto'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/recanto'
  id: '__root__' | '/' | '/recanto'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RecantoRoute: typeof RecantoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/recanto': {
      id: '/recanto'
      path: '/recanto'
      fullPath: '/recanto'
      preLoaderRoute: typeof RecantoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RecantoRoute: RecantoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
